# Generated by Django 5.1.2 on 2024-11-03 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_contest_contestproblem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestproblem',
            name='points',
            field=models.IntegerField(default=20),
        ),
    ]
